/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package popsim;

public class Main {

  public static void main(String[] args) {
    Main main = new Main();
    main.run();
  }

  public void run() {
    World w = new World(8, new RandomWalkerFactory());
    System.out.println(w);
    w.step();
    System.out.println(w);
    w.step();
    System.out.println(w);

    System.out.println("\n\tSimulation Complete!");
  }
}
